import type { GlobalThemeOverrides } from 'naive-ui'

export const lightThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#5f9f35',
    primaryColorHover: '#237d3b',
    primaryColorPressed: '#1b6730',
    primaryColorSuppl: '#88a84a',
    bodyColor: '#f7fbef',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    popoverColor: '#ffffff',
    tableColor: '#ffffff',
    inputColor: '#ffffff',
    actionColor: '#eef7df',
    textColorBase: '#24341f',
    textColor1: '#24341f',
    textColor2: '#57704a',
    textColor3: '#8a9b77',
    dividerColor: '#d9e8c5',
    borderColor: '#d9e8c5',
    hoverColor: 'rgba(95, 159, 53, 0.08)',
    borderRadius: '8px',
    borderRadiusSmall: '6px',
    fontSize: '14px',
    fontSizeMedium: '14px',
    heightMedium: '36px',
    fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
    fontFamilyMono: 'JetBrains Mono, Fira Code, Consolas, monospace',
  },
  Layout: {
    color: '#f7fbef',
    siderColor: '#f3f9e9',
    headerColor: '#f7fbef',
  },
  Menu: {
    itemTextColorActive: '#237d3b',
    itemTextColorActiveHover: '#237d3b',
    itemTextColorChildActive: '#237d3b',
    itemIconColorActive: '#237d3b',
    itemIconColorActiveHover: '#1b6730',
    itemColorActive: 'rgba(95, 159, 53, 0.12)',
    itemColorActiveHover: 'rgba(95, 159, 53, 0.18)',
    arrowColorActive: '#237d3b',
  },
  Button: {
    textColorPrimary: '#ffffff',
    colorPrimary: '#5f9f35',
    colorHoverPrimary: '#237d3b',
    colorPressedPrimary: '#1b6730',
  },
  Input: {
    color: '#ffffff',
    colorFocus: '#ffffff',
    border: '1px solid #d9e8c5',
    borderHover: '1px solid #88a84a',
    borderFocus: '1px solid #5f9f35',
    placeholderColor: '#8a9b77',
    caretColor: '#237d3b',
  },
  Card: {
    color: '#ffffff',
    borderColor: '#d9e8c5',
  },
  Modal: {
    color: '#ffffff',
  },
  Tag: {
    borderRadius: '6px',
  },
}

export const darkThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#a9c957',
    primaryColorHover: '#d8e65a',
    primaryColorPressed: '#efff7c',
    primaryColorSuppl: '#a9c957',
    bodyColor: '#10180f',
    cardColor: '#1d2b19',
    modalColor: '#1d2b19',
    popoverColor: '#1d2b19',
    tableColor: '#1d2b19',
    inputColor: '#162214',
    actionColor: '#172315',
    textColorBase: '#f1f8df',
    textColor1: '#f1f8df',
    textColor2: '#c7d8ad',
    textColor3: '#8fa17c',
    dividerColor: '#324629',
    borderColor: '#324629',
    hoverColor: 'rgba(169, 201, 87, 0.08)',
    borderRadius: '8px',
    borderRadiusSmall: '6px',
    fontSize: '14px',
    fontSizeMedium: '14px',
    heightMedium: '36px',
    fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
    fontFamilyMono: 'JetBrains Mono, Fira Code, Consolas, monospace',
  },
  Layout: {
    color: '#10180f',
    siderColor: '#132011',
    headerColor: '#10180f',
  },
  Menu: {
    itemTextColorActive: '#d8e65a',
    itemTextColorActiveHover: '#d8e65a',
    itemTextColorChildActive: '#d8e65a',
    itemIconColorActive: '#d8e65a',
    itemIconColorActiveHover: '#efff7c',
    itemColorActive: 'rgba(169, 201, 87, 0.14)',
    itemColorActiveHover: 'rgba(169, 201, 87, 0.20)',
    arrowColorActive: '#d8e65a',
  },
  Button: {
    textColorPrimary: '#10180f',
    colorPrimary: '#a9c957',
    colorHoverPrimary: '#d8e65a',
    colorPressedPrimary: '#efff7c',
  },
  Input: {
    color: '#162214',
    colorFocus: '#162214',
    border: '1px solid #324629',
    borderHover: '1px solid #55713a',
    borderFocus: '1px solid #a9c957',
    placeholderColor: '#8fa17c',
    caretColor: '#d8e65a',
  },
  Card: {
    color: '#1d2b19',
    borderColor: '#324629',
  },
  Modal: {
    color: '#1d2b19',
  },
  Tag: {
    borderRadius: '6px',
  },
  Switch: {
    railColor: '#324629',
    railColorActive: '#66bb6a',
    loadingColor: '#a9c957',
    opacityDisabled: 0.4,
  },
}

export function getThemeOverrides(isDark: boolean): GlobalThemeOverrides {
  return isDark ? darkThemeOverrides : lightThemeOverrides
}
