"""OWLS Agent Team — shared interfaces, schemas, and data contracts.

This module is the single source of truth for cross-role type definitions.
It contains NO business logic so that it can be imported safely from any
module without risking circular imports.

Roles:
    @architect  — owner of this file (edit only with architect approval)
    @syseng     — reads SandboxProfile, ToolContext, Interceptor
    @security   — reads AuditEvent, ToolContext, Action, Interceptor
    @agenteng   — reads PlanNode, RiskLevel, Action
    @frontend   — reads AuditEvent, PlanNode (for API serialization)
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal, Protocol, TypedDict

# ---------------------------------------------------------------------------
# Sandbox & Risk
# ---------------------------------------------------------------------------

SandboxProfile = Literal["inspect-ro", "diag-net", "mutate-config", "full-mutate"]
"""Predefined sandbox restriction levels.

- inspect-ro    : read-only filesystem (Landlock RO)
- diag-net      : network diagnostic (unshare CLONE_NEWNET + selective egress)
- mutate-config : limited write (Landlock RW on /etc/, /opt/, OWLS_HOME)
- full-mutate   : minimal restriction, only mandatory checkpoint
"""

RiskLevel = Literal["low", "medium", "high", "critical"]
"""Risk classification for tasks and audit events."""


# ---------------------------------------------------------------------------
# Plan Node (Planner / Executor / Verifier)
# ---------------------------------------------------------------------------

class PlanNode(TypedDict, total=False):
    """One node in an execution plan generated by Planner and tracked by
    PlanStateMachine."""

    id: str
    """Unique node identifier (e.g. 'n_001')."""

    task_desc: str
    """Human-readable description of what this node does."""

    status: Literal["pending", "running", "success", "failed", "rolled_back"]
    """Current execution status."""

    dependencies: list[str]
    """List of node IDs that must complete before this node can start."""

    allowed_tools: list[str]
    """Tool names this node is permitted to invoke."""

    verifier_command: str | None
    """Shell command that must return exit code 0 for this node to be
    considered successful.  None → no verification step."""

    max_retries: int
    """Maximum retry attempts before giving up."""

    sandbox_profile: SandboxProfile
    """Sandbox restriction level applied while this node runs."""

    risk_level: RiskLevel
    """Risk classification used by the interceptor chain."""


# ---------------------------------------------------------------------------
# Audit Event (Security / Frontend)
# ---------------------------------------------------------------------------

class AuditEvent(TypedDict, total=False):
    """Immutable audit record written by AuditLogger.

    All timestamps are ISO-8601 UTC strings.  The SHA-256 chain guarantees
    tamper evidence for offline forensic analysis."""

    event_id: str
    """UUIDv4 — primary key."""

    timestamp: str
    """ISO-8601 UTC when the event occurred."""

    event_type: Literal[
        "tool_call",
        "tool_result",
        "approval_decision",
        "command_execution",
        "command_result",
        "checkpoint_create",
        "checkpoint_restore",
        "policy_violation",
        "rollback_triggered",
        "session_start",
        "session_end",
        "auth_success",
        "auth_failure",
    ]
    """Event classification."""

    session_id: str
    """Gateway or CLI session identifier."""

    task_id: str | None
    """Plan node/task ID when applicable."""

    command: str | None
    """Raw command string for terminal-related events."""

    tool_name: str | None
    """Tool name for tool_call / tool_result events."""

    tool_args: dict[str, Any] | None
    """Tool arguments (sanitised — no secrets)."""

    tool_result: dict[str, Any] | None
    """Tool result summary (truncated if large)."""

    risk_level: RiskLevel
    """Risk at the time of the event."""

    description: str
    """Human-readable description."""

    approved: bool | None
    """Whether the action was approved (for approval_decision events)."""

    pattern_key: str | None
    """Matched pattern key for dangerous-command events."""

    checkpoint_hash: str | None
    """Git commit hash for checkpoint_create / checkpoint_restore."""

    suggested_fix: str | None
    """Suggested remediation for policy_violation events."""

    prev_hash: str
    """SHA-256 of the previous audit line (chain integrity)."""

    hash: str
    """SHA-256 of this event's canonical JSON representation."""

    user: str | None
    """User identifier (for SSH / gateway sessions)."""

    source_ip: str | None
    """Client IP address when available."""


# ---------------------------------------------------------------------------
# Action (Interceptor chain result)
# ---------------------------------------------------------------------------

class Action(TypedDict, total=False):
    """Decision returned by an Interceptor."""

    type: Literal["proceed", "freeze", "rollback"]
    """Decision type:
    - proceed : command may execute
    - freeze  : pause execution, wait for human decision
    - rollback: abort and restore checkpoint
    """

    reason: str | None
    """Human-readable explanation for the decision."""

    suggested_fix: str | None
    """Optional alternative command or remediation hint."""


# ---------------------------------------------------------------------------
# Tool Context (passed to interceptors)
# ---------------------------------------------------------------------------

class ToolContext(TypedDict, total=False):
    """Context object passed through the interceptor chain before a tool
    handler is invoked."""

    command: str
    """Raw command string (for terminal tool)."""

    cwd: str | None
    """Working directory at execution time."""

    tool_name: str
    """Registered tool name (e.g. 'terminal')."""

    target_paths: list[str]
    """Filesystem paths the tool intends to touch."""

    session_id: str
    """Current session identifier."""

    task_id: str | None
    """Plan node/task identifier when running inside a plan."""

    sandbox_profile: SandboxProfile
    """Requested sandbox profile."""

    risk_level: RiskLevel
    """Risk classification for this invocation."""


# ---------------------------------------------------------------------------
# Interceptor Protocol
# ---------------------------------------------------------------------------

class Interceptor(Protocol):
    """A single link in the interceptor chain.

    Implementations must be stateless or store mutable state in external
    stores (e.g. SQLite) so that the same instance can be reused across
    threads and async tasks.
    """

    def intercept(self, ctx: ToolContext) -> Action:
        """Inspect *ctx* and return an Action.

        Returning ``{"type": "proceed"}`` allows the next interceptor (or
        the tool handler) to run.  Any other type short-circuits the chain.
        """
        ...


# ---------------------------------------------------------------------------
# Experience (Agent self-evolution)
# ---------------------------------------------------------------------------

class Experience(TypedDict, total=False):
    """One recorded task execution for the experience store."""

    experience_id: str
    session_id: str
    input_msg: str
    plan_summary: str
    tool_sequence: list[str]
    execution_time_ms: int
    failure_reason: str | None
    user_feedback: str | None
    success: bool
    timestamp: str


class ReflectionReport(TypedDict, total=False):
    """Output of the reflection engine."""

    reflection_id: str
    experience_id: str
    insights: list[str]
    suggested_improvements: list[str]
    prompt_fragment: str | None
    timestamp: str


class PromptFragment(TypedDict, total=False):
    """A distilled prompt template fragment from consolidated experiences."""

    fragment_id: str
    hash: str
    content: str
    source_experience_ids: list[str]
    created_at: str
